version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://salwathurarusiru:PMaSy3DwFdhG2NV7@clusterkalu.chxkj.mongodb.net/mernauth?retryWrites=true&w=majority&appName=clusterkalu
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
volumes:
  mongo-data:
